name: Automation Pipeline

on:
  workflow_dispatch:   # To show "Run workflow" button in GitHub UI to run code manually
  schedule:
    - cron: "30 1 * * *"   # Runs daily automatically at 1:30 ِAM (UTC time zone)

      #┌───────────── minute (0 - 59)
      #│  ┌───────────── hour (0 - 23, UTC)
      #│  │ ┌───────────── day of month (1 - 31)
      #│  │ │ ┌───────────── month (1 - 12)
      #│  │ │ │ ┌───────────── day of week (0 - 6) (Sunday = 0)
      #│  │ │ │ │
      #30 1 * * *

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run automation tests
        #run: mvn clean test
        run: mvn -DtestFailureIgnore=true clean test

      - name: Upload test reports (optional)
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/

      - name: Upload Cucumber HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-report
          path: target/cucumber-html-report.html
